








_G.autorebirth = false 
_G.autoclicker = false
_G.autoegg = false
_G.autounbox = false
_G.autoCraftAll = false 

local head = game:GetService("Players").LocalPlayer.Character.Head
spawn(function()
    while _G.autoclicker == true do
        wait()
        Click()
    end
end)



function Click()
    local remote = game:GetService("ReplicatedStorage").Events.Click3
    remote:FireServer()

end

function unBox(name, mode)
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = name,
    [2] = mode
}

game:GetService("ReplicatedStorage").Functions.Unbox:InvokeServer(unpack(args))


end


function collectEgg()
for i,v in pairs(game:GetService("Workspace").Scripts.Easter:WaitForChild("Eggs").Storage:GetDescendants()) do
    if v.Name == "TouchInterest" and v.Parent then
    firetouchinterest(head, v.Parent, 0)
wait(0.01)
    firetouchinterest(head, v.Parent, 1)
        end
    end
end
spawn(function()
    function rebirth(amount)
        -- Script generated by SimpleSpy - credits to exx#9394
        
        local args = {
            [1] = amount
        }
        
        game:GetService("ReplicatedStorage").Events.Rebirth:FireServer(unpack(args))
        
        end
end)
   
spawn(function()
    function CraftAll()
        -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "CraftAll",
    [2] = {}
}

game:GetService("ReplicatedStorage").Functions.Request:InvokeServer(unpack(args))

    end

    end)



    spawn(function()
        while _G.autorebirth == true do
            wait(0.5)
            rebirth(28)
            end
    end)
    spawn(function()
    while _G.autoegg == true do
    wait(0.05)
    collectEgg()
        end
    end)
        spawn(function()
        while _G.autounbox == true do
        unBox("Easter Part 2", "Triple")
            end
        end)
        spawn(function()
        while _G.autoCraftAll == true do 
          CraftAll()
            end
        
        end)













































local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()
local Window = OrionLib:MakeWindow({Name = "Rebirth Champions X"})


local Main = Window:MakeTab({
	Name = "AutoFarm",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})
local Pets = Window:MakeTab({
	Name = "Pets/Eggs",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})



Pets:AddToggle({
	Name = "AutoCraftAll",
	Default = false,
	Callback = function(Value)
        _G.autounbox = Value 
print(Value)
while _G.autoCraftAll == true do
    wait()
CraftAll() 

        end
    end	    
})

local SelectedMode;
Pets:AddDropdown({
	Name = "Select Mode -- TRIPLE REQUIRES HATCH SPEED",
	Default = "1",
	Options = {"Single", "Triple"},
	Callback = function(Option)
SelectedMode = Option
    end    
})
local eggchoice;
Pets:AddDropdown({
	Name = "Eggs",
	Default = "1",
	Options = {"Chocolate", "Easter", "Easter Part 2", "Forest", "Beach", "Atlantis", "Desert", "Winter", "Magma", "Volcano", "Moon", "Cyber", "Magic", "Heaven", "Nuclear", "Void", "Spooky", "Cave"},
	Callback = function(PetChoice)
eggchoice = PetChoice
	end    
})
local selectedRebirth;
Pets:AddDropdown({
	Name = "Rebirth Options",
	Default = "1",
	Options = {"1", "5", "10", "25", "100", "500", "2.5k", "5k", "10k", "50k", "250k", "1m", "25m", "100m", "500m", "1b", "2.5b", "10b", "250b", "1t", "25t", "100t", "250t", "1Qd", "2.5qd", "10qd", "50qd", "250qd", "1Qn"},
	Callback = function(RebirthO)
        if RebirthO == "1" then
            selectedRebirth = 1;
        elseif RebirthO == "5" then 
            selectedRebirth = 2;
        elseif RebirthO == "10" then
            selectedRebirth = 3;
        elseif RebirthO == "25" then
            selectedRebirth = 4;
        elseif RebirthO == "100" then
            selectedRebirth = 5;
        elseif RebirthO == "500" then
            selectedRebirth = 6;
        elseif RebirthO == "2.5k" then
            selectedRebirth = 7;
        elseif RebirthO == "5k" then
            selectedRebirth = 8;
        elseif RebirthO == "10k" then
            selectedRebirth = 9;
        elseif RebirthO == "50k" then
            selectedRebirth = 10;
        elseif RebirthO == "250k" then
            selectedRebirth = 11;
        elseif RebirthO == "1m" then
            selectedRebirth = 12;
        elseif RebirthO == "25m" then
            selectedRebirth = 13;
        elseif RebirthO == "100m" then
            selectedRebirth = 14;
        elseif RebirthO == "500m" then
            selectedRebirth = 15;

        elseif RebirthO == "1b" then
            selectedRebirth = 16;

        elseif RebirthO == "2.5b" then
            selectedRebirth = 17;
        elseif RebirthO == "10b" then
            selectedRebirth = 18;

        elseif RebirthO == "250b" then
            selectedRebirth = 19;

        elseif RebirthO == "1t" then
            selectedRebirth = 20;
        elseif RebirthO == "100t" then
            selectedRebirth = 21;
        elseif RebirthO == "250t" then
            selectedRebirth = 22;

        elseif RebirthO == "1Qd" then
            selectedRebirth = 23;
        elseif RebirthO == "2.5qd" then
            selectedRebirth = 24;
        elseif RebirthO == "10qd" then
            selectedRebirth = 25;
        elseif RebirthO == "50qd" then
            selectedRebirth = 26;
        elseif RebirthO == "250qd" then
            selectedRebirth = 27;
        elseif RebirthO == "1Qn" then
            selectedRebirth = 28;
            

            
        end

end})



Pets:AddToggle({
	Name = "AutoHatchEgg",
	Default = false,
	Callback = function(Value)
        _G.autounbox = Value 
while _G.autounbox == true do 
unBox(eggchoice, SelectedMode)
        end
    end	    
})

Pets:AddToggle({
	Name = "AutoRebirth",
	Default = false,
	Callback = function(Value)
        _G.autorebirth = Value 
while _G.autorebirth == true do 
    wait()
rebirth(selectedRebirth)
        end
    end	    
})

Main:AddToggle({
	Name = "AutoClick",
	Default = false,
	Callback = function(Value)
        _G.autoclicker = Value 
print(Value)
while _G.autoclicker == true do
    wait()
Click()
    
        end
    end	    
})

Main:AddButton({
	Name = "Collect Easter Eggs",
	Callback = function()
      		collectEgg()
  	end    
})





OrionLib:MakeNotification({
	Name = "First Script!",
	Content = "This is my first script lmao",
	Time = 5
})































